### ISSUE TITLE
ETH driver for PHY DP83TD510E

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS-Driver#11]
Interest in SPE (Single Pair Ethernet) has been growing quickly and the first PHY chips are available on the market.
Is it possible to have and/or develop a CMSIS-driver for PHY [DP83TD510E](https://www.ti.com/product/DP83TD510E) from TI?

If I need to write this driver by myself, where I can find documentation and template files for PHY drivers?

**Comment by RobertRostohar** [comment]
I apologize that this issue was overlooked (notifications were misconfigured).

Is this still relevant?

**Comment by escherstair** [comment]
No, since I bought this driver from another company.
